# Generated by Django 4.0.5 on 2022-06-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summaryTitle', models.CharField(max_length=200)),
                ('summaryNumber', models.CharField(max_length=200)),
                ('totalNumber', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeGalleryTitle', models.CharField(max_length=200)),
                ('image', models.ImageField(max_length=1, null=True, upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=200)),
                ('serviceNumber', models.IntegerField()),
                ('image', models.ImageField(max_length=20, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rsnumber', models.CharField(max_length=200)),
                ('image', models.ImageField(max_length=20, null=True, upload_to='')),
                ('lighttext', models.CharField(max_length=200)),
                ('boldtext', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonialTitle', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=10)),
                ('companyname', models.CharField(max_length=10)),
                ('image', models.ImageField(max_length=1, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
