# Generated by Django 4.0.5 on 2022-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUsTitle', models.CharField(max_length=200)),
                ('image', models.ImageField(max_length=20, null=True, upload_to='images/')),
                ('headingTag', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=200)),
                ('list1', models.CharField(max_length=200)),
                ('list2', models.CharField(max_length=200)),
                ('list3', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
