# Generated by Django 4.0.5 on 2022-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0002_homeaboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyUsTitle', models.CharField(max_length=200)),
                ('image1', models.ImageField(max_length=20, null=True, upload_to='images/')),
                ('image2', models.ImageField(max_length=20, null=True, upload_to='images/')),
                ('headingTag', models.CharField(max_length=200)),
                ('heading1', models.CharField(max_length=200)),
                ('heading2', models.CharField(max_length=200)),
                ('heading3', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
