# Generated by Django 4.0.5 on 2022-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0003_homewhyus'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimony',
            field=models.CharField(default='testimony nkoaa', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='companyname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(max_length=30, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonialTitle',
            field=models.CharField(max_length=20),
        ),
    ]
