# Generated by Django 4.0.5 on 2022-06-10 12:07

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0007_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='my_field',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
