# Generated by Django 4.0.5 on 2022-06-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0008_article_my_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='my_field',
        ),
    ]
