# Generated by Django 4.0.5 on 2022-06-11 20:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0013_alter_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=50)),
                ('image', models.ImageField(max_length=30, null=True, upload_to='')),
                ('titleTag', models.CharField(max_length=50)),
                ('PageTitle', models.CharField(max_length=50)),
                ('contactUs', tinymce.models.HTMLField()),
                ('locationHeading', models.CharField(max_length=50)),
                ('locationText', models.CharField(max_length=50)),
                ('SubText', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('mapUrl', models.CharField(max_length=50)),
            ],
        ),
    ]
