# Generated by Django 4.0.5 on 2022-06-12 13:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0015_rename_pagetitle_contact_locationsubtext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=50)),
                ('serviceTitle', models.ImageField(max_length=30, null=True, upload_to='')),
                ('titleTag', models.CharField(max_length=50)),
                ('pageTitle', models.CharField(max_length=50)),
                ('serviceHeading', models.CharField(max_length=50)),
                ('headingTag', models.CharField(max_length=50)),
                ('servicetext', tinymce.models.HTMLField()),
                ('ourExpertiseHeading', models.CharField(max_length=50)),
                ('expertiseImage', models.ImageField(max_length=30, null=True, upload_to='')),
                ('companyPDF', models.FileField(upload_to='')),
                ('list1', models.CharField(max_length=50)),
                ('list2', models.CharField(max_length=50)),
                ('list3', models.CharField(max_length=50)),
                ('list4', models.CharField(max_length=50)),
                ('telImage', models.ImageField(max_length=30, null=True, upload_to='')),
                ('tel', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='mapUrl',
            field=models.CharField(max_length=1000),
        ),
    ]
