# Generated by Django 4.0.5 on 2022-06-12 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0017_mainabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainabout',
            name='titleTag',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
