# Generated by Django 4.0.5 on 2022-06-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0018_mainabout_titletag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeGallery',
            new_name='Gallery',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='homeGalleryTitle',
            new_name='galleryTitle',
        ),
    ]
