# Generated by Django 4.0.5 on 2022-06-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0020_maingallery_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservices',
            name='backgroundImage',
            field=models.ImageField(max_length=30, null=True, upload_to=''),
        ),
    ]
