# Generated by Django 4.0.5 on 2022-06-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0021_mainservices_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservices',
            name='serviceTag',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mainservices',
            name='serviceTitle',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
