# Generated by Django 4.0.5 on 2022-06-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0022_mainservices_servicetag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=50)),
                ('titleTag', models.CharField(max_length=50)),
                ('image', models.ImageField(max_length=30, null=True, upload_to='')),
            ],
        ),
    ]
