# Generated by Django 4.0.5 on 2022-06-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0023_mainblog'),
        ('mainwebsite', '0023_mainblog_comment'),
    ]

    operations = [
    ]
