# Generated by Django 4.0.5 on 2022-06-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0024_merge_0023_mainblog_0023_mainblog_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
