# Generated by Django 4.0.5 on 2022-06-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0024_blogcomment_delete_comment'),
        ('mainwebsite', '0027_blogcomment_delete_comment'),
    ]

    operations = [
    ]
